FROM ubuntu:24.04

RUN apt-get update && apt-get install -y \
    python3-pip \
    wget \
    iputils-ping \
    iproute2 \
    && rm -rf /var/lib/apt/lists/*

RUN pip3 install cqlsh --break-system-packages

CMD ["tail", "-f", "/dev/null"]